# Add this file to your backend folder:
# render.yaml
services:
  - type: web
    name: gonar-lafiya-api
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT